export const videoConstants = {
  SET_VIDEOS: "SET_VIDEOS",
  HANDLE_WATCH_LATER_VIDEO: "HANDLE_WATCH_LATER_VIDEO",
  SET_EXPLORE_SEARCH_TEXT: "SET_EXPLORE_SEARCH_TEXT",
  SET_SELECTED_PLAYLIST: "SET_SELECTED_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
};
