export const videoConstants = {
  SET_VIDEOS: "SET_VIDEOS",
  HANDLE_WATCH_LATER_VIDEO: "HANDLE_WATCH_LATER_VIDEO",
  SET_EXPLORE_SEARCH_TEXT: "SET_EXPLORE_SEARCH_TEXT",
  SET_SELECTED_PLAYLIST: "SET_SELECTED_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  SET_SHOW_ADD_NEW_PLAYLIST_MODAL: "SET_SHOW_ADD_NEW_PLAYLIST_MODAL",
  ADD_NEW_PLAYLIST: "ADD_NEW_PLAYLIST",
  SET_SHOW_ADD_TO_PLAYLIST_MODAL: "SET_SHOW_ADD_TO_PLAYLIST_MODAL",
  SET_SELECTED_VIDEO: "SET_SELECTED_VIDEO",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
};
